Task no 1

In [1]:
import numpy as np

sensor_data = np.array([
    [12, 15, 14, 10, 13],
    [20, 22, 19, 18, 21],
    [30, 28, 27, 29, 31],
    [25, 24, 26, 23, 22]
])

avg_machine = np.mean(sensor_data, axis=1)

max_time = np.max(sensor_data, axis=0)

normalized = sensor_data / max_time

machines_gt_20 = np.where(avg_machine > 20)

reshaped = sensor_data.reshape(2, 10)

print(avg_machine)
print(max_time)
print(normalized)
print(machines_gt_20)
print(reshaped)

[12.8 20.  29.  24. ]
[30 28 27 29 31]
[[0.4        0.53571429 0.51851852 0.34482759 0.41935484]
 [0.66666667 0.78571429 0.7037037  0.62068966 0.67741935]
 [1.         1.         1.         1.         1.        ]
 [0.83333333 0.85714286 0.96296296 0.79310345 0.70967742]]
(array([2, 3]),)
[[12 15 14 10 13 20 22 19 18 21]
 [30 28 27 29 31 25 24 26 23 22]]


Task no 2

In [2]:
import numpy as np

A = np.random.randint(1, 51, (3, 3))
B = np.random.randint(1, 51, (3, 3))

mat_mul = A @ B

elem_mul = A * B

greater_100 = mat_mul[mat_mul > 100]

A[A < 10] = 0
B[B < 10] = 0

stacked = np.vstack((A, B))

print(A)
print(B)
print(mat_mul)
print(elem_mul)
print(greater_100)
print(stacked)

[[35 14 12]
 [28 16 24]
 [ 0 20 10]]
[[ 0 11 25]
 [14 18 12]
 [10 13 17]]
[[ 386  793 1247]
 [ 520  908 1300]
 [ 388  534  510]]
[[ 70 154 300]
 [392 288 288]
 [ 40 260 170]]
[ 386  793 1247  520  908 1300  388  534  510]
[[35 14 12]
 [28 16 24]
 [ 0 20 10]
 [ 0 11 25]
 [14 18 12]
 [10 13 17]]


Task no 3

In [3]:
import pandas as pd

sales_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "Customer": ["Ali", "Sara", "Ahmed", "Ali", "Zain", "Sara"],
    "City": ["Karachi", "Lahore", "Karachi", "Islamabad", "Lahore", "Karachi"],
    "Category": ["Electronics", "Clothing", "Electronics", "Groceries", "Clothing", "Electronics"],
    "Amount": [12000, 3500, None, 2400, 5200, 15000]
}

df = pd.DataFrame(sales_data)

print(df.head(3))

print(df.isnull())

median_val = df["Amount"].median()

df["Amount"] = df["Amount"].fillna(median_val)

df["Amount"] = df["Amount"].astype(int)

df.to_csv("cleaned_data.csv", index=False)

print(df)

   OrderID Customer     City     Category   Amount
0      101      Ali  Karachi  Electronics  12000.0
1      102     Sara   Lahore     Clothing   3500.0
2      103    Ahmed  Karachi  Electronics      NaN
   OrderID  Customer   City  Category  Amount
0    False     False  False     False   False
1    False     False  False     False   False
2    False     False  False     False    True
3    False     False  False     False   False
4    False     False  False     False   False
5    False     False  False     False   False
   OrderID Customer       City     Category  Amount
0      101      Ali    Karachi  Electronics   12000
1      102     Sara     Lahore     Clothing    3500
2      103    Ahmed    Karachi  Electronics    5200
3      104      Ali  Islamabad    Groceries    2400
4      105     Zain     Lahore     Clothing    5200
5      106     Sara    Karachi  Electronics   15000


Task no 4

In [4]:
df["HighValue"] = df["Amount"] > 10000

karachi_orders = df[df["City"] == "Karachi"]

electronics_high = df[(df["Category"] == "Electronics") & (df["Amount"] > 10000)]

sorted_df = df.sort_values(by="Amount", ascending=False)

top_customers = df.groupby("Customer")["Amount"].sum().sort_values(ascending=False).head(2)

print(karachi_orders)
print(electronics_high)
print(sorted_df)
print(top_customers)

   OrderID Customer     City     Category  Amount  HighValue
0      101      Ali  Karachi  Electronics   12000       True
2      103    Ahmed  Karachi  Electronics    5200      False
5      106     Sara  Karachi  Electronics   15000       True
   OrderID Customer     City     Category  Amount  HighValue
0      101      Ali  Karachi  Electronics   12000       True
5      106     Sara  Karachi  Electronics   15000       True
   OrderID Customer       City     Category  Amount  HighValue
5      106     Sara    Karachi  Electronics   15000       True
0      101      Ali    Karachi  Electronics   12000       True
4      105     Zain     Lahore     Clothing    5200      False
2      103    Ahmed    Karachi  Electronics    5200      False
1      102     Sara     Lahore     Clothing    3500      False
3      104      Ali  Islamabad    Groceries    2400      False
Customer
Sara    18500
Ali     14400
Name: Amount, dtype: int64


Task no 5

In [5]:
total_revenue_city = df.groupby("City")["Amount"].sum()

avg_category = df.groupby("Category")["Amount"].mean()

unique_customers = df.groupby("City")["Customer"].nunique()

pivot = pd.pivot_table(df, values="Amount", index="City", columns="Category", aggfunc="sum")

reset_df = total_revenue_city.reset_index()

print(total_revenue_city)
print(avg_category)
print(unique_customers)
print(pivot)
print(reset_df)


City
Islamabad     2400
Karachi      32200
Lahore        8700
Name: Amount, dtype: int64
Category
Clothing        4350.000000
Electronics    10733.333333
Groceries       2400.000000
Name: Amount, dtype: float64
City
Islamabad    1
Karachi      3
Lahore       2
Name: Customer, dtype: int64
Category   Clothing  Electronics  Groceries
City                                       
Islamabad       NaN          NaN     2400.0
Karachi         NaN      32200.0        NaN
Lahore       8700.0          NaN        NaN
        City  Amount
0  Islamabad    2400
1    Karachi   32200
2     Lahore    8700
